/**
 * Server-side PDF generation for quotations and invoices using pdfkit.
 * Returns a Buffer so the document can be streamed to the client or
 * attached to an outgoing email.
 */
import PDFDocument from 'pdfkit';

const money = (n) => `$${(Number(n) || 0).toFixed(2)}`;
const fmtDate = (v) => {
  const d = v ? new Date(v) : null;
  return d && !isNaN(d.getTime()) ? d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }) : '—';
};

/**
 * Render a document (quote or invoice) to a PDF Buffer.
 * @param {object} opts
 * @param {'QUOTATION'|'INVOICE'} opts.kind
 * @param {object} opts.doc the quote/invoice record
 * @param {object} opts.org issuing organization
 * @param {object} opts.customer customer/company
 */
export function renderDocumentPdf({ kind, doc, org = {}, customer = {} }) {
  return new Promise((resolve, reject) => {
    try {
      const pdf = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];
      pdf.on('data', (c) => chunks.push(c));
      pdf.on('end', () => resolve(Buffer.concat(chunks)));
      pdf.on('error', reject);

      const accent = '#2563eb';

      // Header
      pdf.fillColor(accent).fontSize(22).text(org.name || 'EquipTrack Pro', 50, 50);
      pdf.fillColor('#666').fontSize(9)
        .text(org.address || '', 50, 78)
        .text([org.email, org.phone].filter(Boolean).join('  |  '), 50, 90);

      pdf.fillColor('#111').fontSize(26).text(kind, 400, 50, { align: 'right' });
      pdf.fillColor('#666').fontSize(10).text(`# ${doc.number || doc.id}`, 400, 84, { align: 'right' });

      // Meta block
      let y = 130;
      pdf.fillColor('#111').fontSize(10).font('Helvetica-Bold').text('Bill To', 50, y);
      pdf.font('Helvetica').fillColor('#333')
        .text(customer.name || 'Customer', 50, y + 14)
        .text(customer.address || '', 50, y + 28)
        .text(customer.email || '', 50, y + 42);

      const rightX = 330;
      const dateLabel = kind === 'INVOICE' ? 'Issue Date' : 'Issue Date';
      const dueLabel = kind === 'INVOICE' ? 'Due Date' : 'Valid Until';
      pdf.fillColor('#111').font('Helvetica-Bold')
        .text(dateLabel, rightX, y, { width: 100 })
        .text(dueLabel, rightX, y + 16, { width: 100 })
        .text('Status', rightX, y + 32, { width: 100 });
      pdf.font('Helvetica').fillColor('#333')
        .text(fmtDate(doc.issueDate), rightX + 110, y, { width: 105, align: 'right' })
        .text(fmtDate(doc.dueDate || doc.validUntil), rightX + 110, y + 16, { width: 105, align: 'right' })
        .text(String(doc.status || '').toUpperCase(), rightX + 110, y + 32, { width: 105, align: 'right' });

      // Table header
      y = 220;
      pdf.rect(50, y, 495, 22).fill(accent);
      pdf.fillColor('#fff').fontSize(9).font('Helvetica-Bold')
        .text('Description', 58, y + 6)
        .text('Qty', 300, y + 6, { width: 40, align: 'right' })
        .text('Days', 345, y + 6, { width: 40, align: 'right' })
        .text('Rate', 400, y + 6, { width: 60, align: 'right' })
        .text('Amount', 470, y + 6, { width: 67, align: 'right' });

      y += 22;
      pdf.font('Helvetica').fillColor('#111').fontSize(9);
      (doc.lineItems || []).forEach((li, i) => {
        if (i % 2 === 0) pdf.rect(50, y, 495, 20).fill('#f5f7fa');
        pdf.fillColor('#111')
          .text(li.description || '—', 58, y + 6, { width: 235 })
          .text(String(li.qty ?? 1), 300, y + 6, { width: 40, align: 'right' })
          .text(String(li.days ?? 1), 345, y + 6, { width: 40, align: 'right' })
          .text(money(li.rate), 400, y + 6, { width: 60, align: 'right' })
          .text(money(li.amount), 470, y + 6, { width: 67, align: 'right' });
        y += 20;
      });

      // Totals
      y += 12;
      const totalsRow = (label, val, bold) => {
        pdf.font(bold ? 'Helvetica-Bold' : 'Helvetica').fillColor('#111').fontSize(10)
          .text(label, 360, y, { width: 100, align: 'right' })
          .text(money(val), 470, y, { width: 67, align: 'right' });
        y += 16;
      };
      totalsRow('Subtotal', doc.subtotal);
      if (doc.discount) totalsRow('Discount', -doc.discount);
      totalsRow(`Tax (${Math.round((doc.taxRate || 0) * 100)}%)`, doc.taxAmount);
      pdf.moveTo(360, y).lineTo(537, y).stroke('#ccc'); y += 6;
      totalsRow('Total', doc.total, true);
      if (kind === 'INVOICE') {
        totalsRow('Paid', doc.amountPaid || 0);
        totalsRow('Balance Due', (doc.total || 0) - (doc.amountPaid || 0), true);
      }

      // Notes / footer
      if (doc.notes) {
        y += 20;
        pdf.font('Helvetica-Bold').fillColor('#111').fontSize(9).text('Notes', 50, y);
        pdf.font('Helvetica').fillColor('#555').text(doc.notes, 50, y + 14, { width: 480 });
      }
      pdf.fontSize(8).fillColor('#999').text(`Generated by EquipTrack Pro`, 50, 790, { align: 'center', width: 495 });

      pdf.end();
    } catch (err) {
      reject(err);
    }
  });
}
