import { Company, Person, Equipment, Project, RentalAgreement, MaintenanceRecord, ConditionReport, Delivery } from './types';

// Mock Companies
export const mockCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'BuildRight Construction',
    category: 'construction',
    contact: {
      email: 'contact@buildright.com',
      phone: '555-0101',
      address: '123 Construction Ave, City, State',
    },
    canRentEquipment: true,
    canProvideEquipment: true,
    status: 'active',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'comp-2',
    name: 'Pro Event Solutions',
    category: 'events',
    contact: {
      email: 'info@proevents.com',
      phone: '555-0102',
      address: '456 Event Street, City, State',
    },
    canRentEquipment: true,
    canProvideEquipment: true,
    status: 'active',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'comp-3',
    name: 'Industrial Machinery Co',
    category: 'manufacturing',
    contact: {
      email: 'sales@industrial-mach.com',
      phone: '555-0103',
      address: '789 Industrial Way, City, State',
    },
    canRentEquipment: false,
    canProvideEquipment: true,
    status: 'active',
    createdAt: new Date('2024-01-20'),
  },
];

// Mock People
export const mockPeople: Person[] = [
  {
    id: 'person-1',
    name: 'John Smith',
    email: 'john@buildright.com',
    companyId: 'comp-1',
    role: 'admin',
    assignedEquipment: ['equip-1', 'equip-2'],
    activeRentals: ['rental-1'],
    status: 'active',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'person-2',
    name: 'Sarah Johnson',
    email: 'sarah@buildright.com',
    companyId: 'comp-1',
    role: 'manager',
    assignedEquipment: ['equip-3'],
    activeRentals: ['rental-2'],
    status: 'active',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'person-3',
    name: 'Mike Davis',
    email: 'mike@proevents.com',
    companyId: 'comp-2',
    role: 'operator',
    assignedEquipment: ['equip-5', 'equip-6'],
    activeRentals: [],
    status: 'active',
    createdAt: new Date('2024-02-05'),
  },
  {
    id: 'person-4',
    name: 'Emily Chen',
    email: 'emily@industrial-mach.com',
    companyId: 'comp-3',
    role: 'manager',
    assignedEquipment: [],
    activeRentals: [],
    status: 'active',
    createdAt: new Date('2024-01-25'),
  },
];

// Mock Equipment
export const mockEquipment: Equipment[] = [
  {
    id: 'equip-1',
    name: 'Excavator CAT 320',
    description: 'Heavy duty excavator for digging and earthmoving',
    category: 'construction-excavators',
    ownerCompanyId: 'comp-1',
    status: 'in-use',
    pricingType: 'daily',
    fixedRate: 450,
    assignedPersonId: 'person-1',
    assignedProjectId: 'proj-1',
    location: 'Job Site A',
    certifications: ['Heavy Equipment Operation'],
    condition: 'good',
    lastMaintenance: new Date('2024-05-10'),
    specifications: {
      'Bucket Capacity': '1.0 cubic meter',
      'Engine Power': '140 HP',
      'Max Reach': '10.3 meters',
    },
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'equip-2',
    name: 'Concrete Mixer',
    description: 'Portable concrete mixer for job site use',
    category: 'construction-tools',
    ownerCompanyId: 'comp-1',
    status: 'available',
    pricingType: 'both',
    fixedRate: 80,
    hourlyRate: 15,
    location: 'Warehouse A',
    certifications: [],
    condition: 'excellent',
    lastMaintenance: new Date('2024-05-15'),
    specifications: {
      'Capacity': '450 liters',
      'Power': '2 HP',
      'Weight': '350 kg',
    },
    createdAt: new Date('2024-01-12'),
  },
  {
    id: 'equip-3',
    name: 'Forklift Toyota 5FGU45',
    description: 'Industrial forklift for material handling',
    category: 'construction-forklifts',
    ownerCompanyId: 'comp-1',
    status: 'rented-out',
    pricingType: 'daily',
    fixedRate: 120,
    assignedPersonId: 'person-2',
    location: 'Client Site B',
    certifications: ['Forklift Operation', 'Safety Certification'],
    condition: 'good',
    lastMaintenance: new Date('2024-05-18'),
    specifications: {
      'Lift Height': '4.8 meters',
      'Capacity': '2000 kg',
      'Mast Type': 'Triple Stage',
    },
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'equip-4',
    name: 'Pro Sound System 3000',
    description: 'Professional audio system for large events',
    category: 'events-audio',
    ownerCompanyId: 'comp-2',
    status: 'maintenance',
    pricingType: 'daily',
    fixedRate: 350,
    location: 'Service Center',
    certifications: ['Audio Engineering'],
    condition: 'fair',
    lastMaintenance: new Date('2024-05-20'),
    specifications: {
      'Output': '10,000W RMS',
      'Frequency': '20Hz-20kHz',
      'Inputs': '24 channels',
    },
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'equip-5',
    name: 'LED Lighting Rig 500',
    description: 'Professional stage lighting setup',
    category: 'events-lighting',
    ownerCompanyId: 'comp-2',
    status: 'available',
    pricingType: 'both',
    fixedRate: 200,
    hourlyRate: 40,
    location: 'Warehouse B',
    certifications: ['Electrical Safety'],
    condition: 'excellent',
    lastMaintenance: new Date('2024-05-16'),
    specifications: {
      'Power': '5000W',
      'Color Output': 'RGB + White',
      'Coverage': '150 meters diameter',
    },
    createdAt: new Date('2024-02-03'),
  },
  {
    id: 'equip-6',
    name: 'Event Tent 50x30',
    description: 'Large event tent for outdoor gatherings',
    category: 'events-tents',
    ownerCompanyId: 'comp-2',
    status: 'in-use',
    pricingType: 'daily',
    fixedRate: 300,
    assignedPersonId: 'person-3',
    assignedProjectId: 'proj-2',
    location: 'Event Venue',
    certifications: [],
    condition: 'excellent',
    lastMaintenance: new Date('2024-05-19'),
    specifications: {
      'Size': '50m x 30m',
      'Height': '6 meters',
      'Capacity': '500 people',
    },
    createdAt: new Date('2024-02-05'),
  },
  {
    id: 'equip-7',
    name: 'CNC Milling Machine 5-Axis',
    description: 'Precision CNC machine for manufacturing',
    category: 'manufacturing-cnc',
    ownerCompanyId: 'comp-3',
    status: 'available',
    pricingType: 'hourly',
    hourlyRate: 150,
    location: 'Factory A',
    certifications: ['CNC Operation', 'Machine Safety'],
    condition: 'excellent',
    lastMaintenance: new Date('2024-05-12'),
    specifications: {
      'Spindle Speed': '10,000 RPM',
      'Accuracy': '±0.02mm',
      'Table Size': '2000x1000mm',
    },
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'equip-8',
    name: 'Industrial Compressor 150 PSI',
    description: 'Heavy duty air compressor',
    category: 'manufacturing-tools',
    ownerCompanyId: 'comp-3',
    status: 'damaged',
    pricingType: 'daily',
    fixedRate: 90,
    location: 'Maintenance Shop',
    certifications: ['Pressure Equipment'],
    condition: 'poor',
    lastMaintenance: new Date('2024-04-20'),
    specifications: {
      'Output': '500 CFM',
      'Pressure': '150 PSI',
      'Power': '25 HP',
    },
    createdAt: new Date('2024-01-25'),
  },
];

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Downtown Office Complex',
    description: 'Large commercial office building construction',
    companyId: 'comp-1',
    status: 'active',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-08-31'),
    assignedEquipment: ['equip-1', 'equip-3'],
    assignedPeople: ['person-1', 'person-2'],
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'proj-2',
    name: 'Summer Music Festival 2024',
    description: 'Large outdoor music festival',
    companyId: 'comp-2',
    status: 'active',
    startDate: new Date('2024-06-15'),
    endDate: new Date('2024-06-17'),
    assignedEquipment: ['equip-4', 'equip-5', 'equip-6'],
    assignedPeople: ['person-3'],
    createdAt: new Date('2024-05-01'),
  },
  {
    id: 'proj-3',
    name: 'Industrial Parts Manufacturing Q2',
    description: 'Manufacturing contract for automotive parts',
    companyId: 'comp-3',
    status: 'planning',
    startDate: new Date('2024-07-01'),
    endDate: new Date('2024-09-30'),
    assignedEquipment: ['equip-7'],
    assignedPeople: ['person-4'],
    createdAt: new Date('2024-05-10'),
  },
];

// Mock Rental Agreements
export const mockRentals: RentalAgreement[] = [
  {
    id: 'rental-1',
    rentalCompanyId: 'comp-2',
    equipmentProviderCompanyId: 'comp-1',
    equipmentIds: ['equip-2'],
    assignedPersonId: 'person-3',
    projectId: 'proj-2',
    startDate: new Date('2024-06-10'),
    endDate: new Date('2024-06-18'),
    pricingModel: 'daily',
    estimatedCost: 640,
    actualCost: 640,
    status: 'completed',
    notes: 'Summer festival preparation - concrete mixer rental',
    createdAt: new Date('2024-06-01'),
  },
  {
    id: 'rental-2',
    rentalCompanyId: 'comp-2',
    equipmentProviderCompanyId: 'comp-1',
    equipmentIds: ['equip-3'],
    assignedPersonId: 'person-2',
    projectId: 'proj-1',
    startDate: new Date('2024-05-20'),
    endDate: new Date('2024-06-03'),
    pricingModel: 'daily',
    estimatedCost: 1680,
    actualCost: 1680,
    status: 'active',
    notes: 'Forklift for materials handling',
    createdAt: new Date('2024-05-15'),
  },
  {
    id: 'rental-3',
    rentalCompanyId: 'comp-1',
    equipmentProviderCompanyId: 'comp-3',
    equipmentIds: ['equip-7'],
    assignedPersonId: 'person-1',
    startDate: new Date('2024-06-01'),
    endDate: new Date('2024-06-05'),
    pricingModel: 'hourly',
    estimatedCost: 3600,
    hoursUsed: 24,
    actualCost: 3600,
    status: 'active',
    notes: 'CNC machine rental for custom fabrication',
    createdAt: new Date('2024-05-25'),
  },
  {
    id: 'rental-4',
    rentalCompanyId: 'comp-2',
    equipmentProviderCompanyId: 'comp-1',
    equipmentIds: ['equip-1'],
    assignedPersonId: 'person-3',
    projectId: 'proj-2',
    startDate: new Date('2024-05-25'),
    endDate: new Date('2024-06-10'),
    pricingModel: 'daily',
    estimatedCost: 6750,
    actualCost: 6750,
    status: 'active',
    notes: 'Excavator for site preparation',
    createdAt: new Date('2024-05-20'),
  },
];

// Mock Maintenance Records
export const mockMaintenance: MaintenanceRecord[] = [
  {
    id: 'maint-1',
    equipmentId: 'equip-1',
    type: 'preventive',
    scheduledDate: new Date('2024-06-10'),
    description: 'Regular oil change and filter replacement',
    cost: 250,
    status: 'scheduled',
    createdAt: new Date('2024-05-20'),
  },
  {
    id: 'maint-2',
    equipmentId: 'equip-4',
    type: 'corrective',
    scheduledDate: new Date('2024-05-25'),
    completedDate: new Date('2024-05-27'),
    description: 'Amplifier repair and recalibration',
    cost: 500,
    status: 'completed',
    notes: 'Replaced power module, all systems tested',
    createdAt: new Date('2024-05-20'),
  },
  {
    id: 'maint-3',
    equipmentId: 'equip-8',
    type: 'corrective',
    scheduledDate: new Date('2024-05-21'),
    completedDate: new Date('2024-05-25'),
    description: 'Motor bearing replacement and rebuild',
    cost: 800,
    status: 'completed',
    notes: 'Major overhaul needed due to damage',
    createdAt: new Date('2024-05-20'),
  },
  {
    id: 'maint-4',
    equipmentId: 'equip-2',
    type: 'preventive',
    scheduledDate: new Date('2024-06-15'),
    description: 'Blade inspection and replacement',
    cost: 150,
    status: 'scheduled',
    createdAt: new Date('2024-05-30'),
  },
];

// Mock Condition Reports
export const mockConditionReports: ConditionReport[] = [
  {
    id: 'cond-1',
    equipmentId: 'equip-8',
    reportedDate: new Date('2024-05-20'),
    reportedBy: 'person-4',
    damageLevel: 'severe',
    description: 'Motor bearing making grinding noise, equipment unsafe',
    repairRequired: true,
    photos: [],
    createdAt: new Date('2024-05-20'),
  },
  {
    id: 'cond-2',
    equipmentId: 'equip-1',
    reportedDate: new Date('2024-05-18'),
    reportedBy: 'person-1',
    damageLevel: 'minor',
    description: 'Small dent on bucket, cosmetic damage only',
    repairRequired: false,
    createdAt: new Date('2024-05-18'),
  },
  {
    id: 'cond-3',
    equipmentId: 'equip-4',
    reportedDate: new Date('2024-05-22'),
    reportedBy: 'person-3',
    damageLevel: 'moderate',
    description: 'Audio crackling in left channel, output reduced',
    repairRequired: true,
    createdAt: new Date('2024-05-22'),
  },
];

// Mock Deliveries
export const mockDeliveries: Delivery[] = [
  {
    id: 'deliv-1',
    equipmentIds: ['equip-2'],
    fromCompanyId: 'comp-1',
    toCompanyId: 'comp-2',
    pickupDate: new Date('2024-06-09'),
    deliveryDate: new Date('2024-06-10'),
    status: 'delivered',
    driver: 'John',
    notes: 'Delivered to event site A',
    createdAt: new Date('2024-06-05'),
  },
  {
    id: 'deliv-2',
    equipmentIds: ['equip-1'],
    fromCompanyId: 'comp-1',
    toCompanyId: 'comp-2',
    pickupDate: new Date('2024-05-24'),
    deliveryDate: new Date('2024-05-25'),
    status: 'delivered',
    driver: 'Mike',
    createdAt: new Date('2024-05-20'),
  },
  {
    id: 'deliv-3',
    equipmentIds: ['equip-3'],
    fromCompanyId: 'comp-1',
    toCompanyId: 'comp-2',
    pickupDate: new Date('2024-06-05'),
    deliveryDate: new Date('2024-06-07'),
    status: 'in-transit',
    driver: 'Sarah',
    createdAt: new Date('2024-06-01'),
  },
];

// Mock Notifications
export const mockNotifications = [
  {
    id: 'notif-1',
    type: 'late-return',
    title: 'Late Return Alert',
    message: 'Excavator CAT 320 (equip-1) is overdue - returned 2 days late',
    recipients: ['person-1', 'person-2'],
    priority: 'high',
    status: 'unread',
    createdAt: new Date('2024-06-05'),
  },
  {
    id: 'notif-2',
    type: 'maintenance-due',
    title: 'Maintenance Scheduled',
    message: 'Forklift Toyota 5FGU45 is due for maintenance on June 10th',
    recipients: ['person-2'],
    priority: 'medium',
    status: 'unread',
    createdAt: new Date('2024-06-04'),
  },
  {
    id: 'notif-3',
    type: 'damage-report',
    title: 'Damage Reported',
    message: 'Industrial Compressor 150 PSI has been reported with severe damage',
    recipients: ['person-4', 'emily@industrial-mach.com'],
    priority: 'high',
    status: 'read',
    createdAt: new Date('2024-05-20'),
  },
  {
    id: 'notif-4',
    type: 'equipment-available',
    title: 'Equipment Available',
    message: 'LED Lighting Rig 500 is now available for booking',
    recipients: ['comp-1', 'comp-2'],
    priority: 'low',
    status: 'read',
    createdAt: new Date('2024-06-01'),
  },
];

// Mock Penalties
export const mockPenalties = [
  {
    id: 'penalty-1',
    rentalId: 'rental-4',
    type: 'late-return',
    amount: 675,
    daysOverdue: 3,
    description: 'Late return charge: 3 days x $225/day',
    status: 'pending',
    createdAt: new Date('2024-06-10'),
  },
  {
    id: 'penalty-2',
    rentalId: 'rental-2',
    type: 'damage',
    amount: 450,
    description: 'Damage claim: Dent on bucket requiring repair',
    status: 'pending',
    createdAt: new Date('2024-05-25'),
  },
  {
    id: 'penalty-3',
    rentalId: 'rental-1',
    type: 'late-return',
    amount: 160,
    daysOverdue: 1,
    description: 'Late return charge: 1 day x $160/day',
    status: 'paid',
    paidDate: new Date('2024-06-20'),
    createdAt: new Date('2024-06-18'),
  },
];

// Mock Support Tickets
export const mockTickets = [
  {
    id: 'ticket-1',
    title: 'Equipment Quality Issue',
    description: 'Audio system has crackling in one channel',
    customerId: 'comp-2',
    equipmentId: 'equip-4',
    priority: 'high',
    status: 'open',
    assignedTo: 'person-1',
    messages: [
      {
        id: 'msg-1',
        sender: 'comp-2',
        content: 'The audio system has crackling sounds coming from the left channel.',
        timestamp: new Date('2024-05-22'),
      },
      {
        id: 'msg-2',
        sender: 'person-1',
        content: 'We are working on repairing the amplifier. Should be done by tomorrow.',
        timestamp: new Date('2024-05-23'),
      },
    ],
    createdAt: new Date('2024-05-22'),
  },
  {
    id: 'ticket-2',
    title: 'Schedule Conflict',
    description: 'Cannot find equipment availability for requested dates',
    customerId: 'comp-1',
    priority: 'medium',
    status: 'open',
    assignedTo: 'person-2',
    messages: [
      {
        id: 'msg-3',
        sender: 'comp-1',
        content: 'Need CNC machine from June 8-12 but it shows booked.',
        timestamp: new Date('2024-06-02'),
      },
    ],
    createdAt: new Date('2024-06-02'),
  },
];

// Mock Calendar Events
export const mockCalendarEvents = [
  {
    id: 'cal-1',
    equipmentId: 'equip-1',
    eventType: 'rental',
    startDate: new Date('2024-06-10'),
    endDate: new Date('2024-06-20'),
    rentalId: 'rental-4',
    company: 'BuildRight Construction',
    status: 'active',
  },
  {
    id: 'cal-2',
    equipmentId: 'equip-2',
    eventType: 'maintenance',
    startDate: new Date('2024-06-15'),
    endDate: new Date('2024-06-16'),
    maintenanceId: 'maint-4',
    description: 'Blade inspection and replacement',
    status: 'scheduled',
  },
  {
    id: 'cal-3',
    equipmentId: 'equip-3',
    eventType: 'rental',
    startDate: new Date('2024-05-20'),
    endDate: new Date('2024-06-03'),
    rentalId: 'rental-2',
    company: 'Pro Event Solutions',
    status: 'active',
  },
  {
    id: 'cal-4',
    equipmentId: 'equip-5',
    eventType: 'available',
    startDate: new Date('2024-06-01'),
    endDate: new Date('2024-06-30'),
    status: 'available',
  },
];
